// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTXh4mtca-vhGcez4M7Xr3xr4KoLzHOfg',
    appId: '1:189774954357:web:9a700a4e5eedef43fc9d3c',
    messagingSenderId: '189774954357',
    projectId: 'aber-53d81',
    authDomain: 'aber-53d81.firebaseapp.com',
    storageBucket: 'aber-53d81.firebasestorage.app',
    measurementId: 'G-7Z4XBB43NK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6ylqKdQSqQc65iAkTITDoh632o5i2wmE',
    appId: '1:189774954357:android:af83cd2fad1014b2fc9d3c',
    messagingSenderId: '189774954357',
    projectId: 'aber-53d81',
    storageBucket: 'aber-53d81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc2h-xbtkML3OQU4JUEaJqa0DBEgK4_c0',
    appId: '1:189774954357:ios:372b80df806885defc9d3c',
    messagingSenderId: '189774954357',
    projectId: 'aber-53d81',
    storageBucket: 'aber-53d81.firebasestorage.app',
    iosBundleId: 'com.aber.aber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc2h-xbtkML3OQU4JUEaJqa0DBEgK4_c0',
    appId: '1:189774954357:ios:372b80df806885defc9d3c',
    messagingSenderId: '189774954357',
    projectId: 'aber-53d81',
    storageBucket: 'aber-53d81.firebasestorage.app',
    iosBundleId: 'com.aber.aber',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTXh4mtca-vhGcez4M7Xr3xr4KoLzHOfg',
    appId: '1:189774954357:web:891dff55c14ace3efc9d3c',
    messagingSenderId: '189774954357',
    projectId: 'aber-53d81',
    authDomain: 'aber-53d81.firebaseapp.com',
    storageBucket: 'aber-53d81.firebasestorage.app',
    measurementId: 'G-NT9DFX2HW0',
  );
}
